apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.ingressname.xapp-onboarder" . }}-chartmuseum
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ include "common.kongpath.ric.chartmuseum" . }}
        backend:
          service:
            name: {{ include "common.servicename.xapp-onboarder.server" . }}
            port:
              number: {{ include "common.serviceport.xapp-onboarder.chartmuseum" . }}
