apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.ingressname.a1mediator" . }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ include "common.kongpath.ric.a1mediator" . }}
        backend:
          service:
            name: {{ include "common.servicename.a1mediator.http" . }}
            port:
              number: {{ include "common.serviceport.a1mediator.http" . }}
